export enum TPeerAction {
  PING = "PING",
  JOIN = "JOIN",
  RECONNECT = "RECONNECT",
  PUSH_DATA = "PUSH_DATA",
  PULL_DATA = "PULL_DATA",
  OPEN_POSITION = "OPEN_POSITION",
  CLOSE_POSITION = "CLOSE_POSITION",
  START_GAME = "START_GAME",
  END_GAME = "END_GAME",
}
