export enum TPeerAction {
  PING = "PING",
  JOIN = "JOIN",
  RECONNECT = "RECONNECT",
  PUSH_SHARED = "PUSH_SHARED",
  PULL_SHARED = "PULL_SHARED",
  PUSH_PRIVATE = "PUSH_PRIVATE",
  OPEN_POSITION = "OPEN_POSITION",
  CLOSE_POSITION = "CLOSE_POSITION",
  START_GAME = "START_GAME",
  END_GAME = "END_GAME",
}
